### ISSUE TITLE
Renaming "trial_id" to "trial_num" in /main/state/state.py

### ISSUE THREAD

**Issue by Rudra-23** [fostiropoulos/ablator#109]
In state.py, there are some statements like:
* `trial_id = int(trial.trial_num)`
* `stmt = select(Trial).where(Trial.trial_num == trial_id)`

The variable naming is misleading, since `trial_id` is the entry id in the DB and `trial_num` is the number associated with the sampler.
Therefore, `trial_id` in the code should be renamed to `trial_num`.

**Comment by fostiropoulos** [comment]
Fixed:
https://github.com/fostiropoulos/ablator/commit/6df267ccea9cc41678daaeb477d05a9c2506c658
