### ISSUE TITLE
Typo in modules/scheduler.py

### ISSUE THREAD

**Issue by hieuchi911** [fostiropoulos/ablator#15]
In `modules/scheduler.py`, config class for `ReduceLROnPlateau` scheduler has a typo. It's `PlateuaConfig`, while it's supposed to be 'PlateauConfig'

**Comment by hieuchi911** [comment]
Not addressed in `examples` branch yet

**Comment by fostiropoulos** [comment]
Should be fixed:

https://github.com/fostiropoulos/ablator/commit/5d327789b8a42d0463260a76ee6134b781cbcd01
