### ISSUE TITLE
Incorrect functional call run_config.gcp_config.rsync_down_node

### ISSUE THREAD

**Issue by hieuchi911** [fostiropoulos/ablator#20]
In `ablator.main.mp.py`, `_rsync_nodes()` method makes a call on the GCP config object: `self.run_config.gcp_config.rsync_down_node(hostname, self.experiment_dir, self.logger)`, but I can only find in GcpConfig class a method named `rsync_down_nodes` in `ablator.modules.storage.cloud.py`. Is this a bug?

**Comment by fostiropoulos** [comment]
Good catch! Fixed: https://github.com/fostiropoulos/ablator/commit/8d9c4ad523a3160b1359a61df1e3a302bcb76aa0
