### ISSUE TITLE
Misleading naming of optim_direction in parse_metrics() in main.mp

### ISSUE THREAD

**Issue by hieuchi911** [fostiropoulos/ablator#22]
The naming of `optim_direction` parameter in `parse_metrics()` function is misleading, since when it's called: `metrics =parse_metrics(list(self.run_config.optim_metrics.keys()), metrics)`, `self.run_config.optim_metrics.keys()` returns metrics names, not optimization direction.

**Comment by fostiropoulos** [comment]
Should be fixed
